# Hard Drive Fornsics

## Redhat
- name: "Mobile packages"
  package: name={{ item }} state=present
  with_items:
    - android-tools
  when: ansible_os_family == "Redhat"

## Debian
- name: "Mobile packages"
  package: name={{ item }} state=present
  with_items:
    - android-tools-adb
    - android-tools-fastboot
  when: ansible_os_family == "Debian"
