---

- name: "Creating exploitation directory"
  file: path={{ tools_root }}/exploitation owner=root group=root state=directory mode=0755

## Redhat

- name: "Exploitation packages"
  package: name={{ item }} state=present
  with_items:
    - sqlninja
  when: ansible_distribution == 'Fedora'

  #TODO: bundle install
- name: "Metasploit: Allow local connections to postgres for Metasploit setup"
  replace: dest=/var/lib/pgsql/data/pg_hba.conf
           regexp='local\s+all\s+all\s+peer'
           replace='local all all trust'
  notify: 
    - restart postgresql
  when: ansible_os_family == "RedHat"
- name: "Metasploit: Allow local connections to postgres for Metasploit setup"
  replace: dest=/etc/postgresql/9.4/main/pg_hba.conf
           regexp='local\s+all\s+postgres\s+peer'
           replace='local all postgres trust'
  notify: 
    - restart postgresql
  when: ansible_os_family == "Debian"
- meta: flush_handlers
- name: "Metasploit: Git"
  git: repo=https://github.com/rapid7/metasploit-framework.git dest={{ tools_root }}/exploitation/metasploit
- name: "Metasploit: Postgres user"
  postgresql_user: name=msf password=msf role_attr_flags=NOSUPERUSER,NOCREATEROLE,NOCREATEDB
- name: "Metasploit: Postgres DB"
  postgresql_db: name=msf owner=msf
- name: "Metasploit: database.yml config"
  template: src=msf-database.yml.j2 dest={{ tools_root }}/exploitation/metasploit/config/database.yml mode=0640
- name: "Metasploit: Add line in pg_hba.conf"
  lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
              regexp='host\s+msf\s+msf\s+127.0.0.1/32\s+md5'
              line='host msf msf 127.0.0.1/32 md5'
              insertafter='#\s+TYPE\s+DATABASE\s+USER'
              state=present
  when: ansible_os_family == "RedHat"
- name: "Metasploit: Add line in pg_hba.conf"
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              regexp='host\s+msf\s+msf\s+127.0.0.1/32\s+md5'
              line='host msf msf 127.0.0.1/32 md5'
              insertafter='#\s+TYPE\s+DATABASE\s+USER'
              state=present
  when: ansible_os_family == "Debian"
- name: "Metasploit: Reset local postgresql connections to 'peer' after Metasploit setup"
  replace: dest=/var/lib/pgsql/data/pg_hba.conf
           regexp='local\s+all\s+all\s+trust'
           replace='local all all peer'
  notify:
    - restart postgresql
  when: ansible_os_family == "RedHat"
- name: "Metasploit: Reset local postgresql connections to 'peer' after Metasploit setup"
  replace: dest=/etc/postgresql/9.4/main/pg_hba.conf
           regexp='local\s+all\s+postgres\s+trust'
           replace='local all postgres peer'
  notify:
    - restart postgresql
  when: ansible_os_family == "Debian"

- meta: flush_handlers

- name: "git clone BeEF"
  git: repo=https://github.com/beefproject/beef.git dest={{ tools_root }}/exploitation/beef

- name: "Burp: Creating /opt/burp directory"
  file: path={{ tools_root }}/exploitation/burp owner=root group=root state=directory mode=0700
  tags: gui
#- name: "Download: Burp Suite"
#  get_url: url=http://portswigger.net/burp/burpsuite_free_v1.6.01.jar dest={{ tools_root }}/exploitation/burp mode=0755
#  tags: gui
- name: "Burp Wrapper"
  copy: src=burp dest=/usr/bin/burp mode=0755
  tags: gui

- name: "git clone exploit-db"
  git: 
    repo: https://github.com/offensive-security/exploit-database.git 
    clone: yes
    dest: "{{ tools_root }}/exploitation/exploit-db"
    force: no
  tags: exploitdb

- name: "git clone FuzzDB"
  git: repo=https://github.com/fuzzdb-project/fuzzdb.git dest={{ tools_root }}/exploitation/fuzzdb

- name: "git clone jboss-autopwn"
  git: repo=https://github.com/SpiderLabs/jboss-autopwn dest={{ tools_root }}/exploitation/jboss-autopwn

- name: "git clone Leroy-Jenkins"
  git: repo=https://github.com/captainhooligan/Leroy-Jenkins.git dest={{ tools_root }}/exploitation/leroy-jenkins

- name: "git clone lisa"
  git: repo=https://github.com/ant4g0nist/lisa.py dest={{ tools_root }}/exploitation/lisa

- name: "git clone NoSQLMap"
  git: repo=https://github.com/tcstool/NoSQLMap.git dest={{ tools_root }}/exploitation/nosqlmap

- name: "git clone peda"
  git: repo=https://github.com/zachriggle/peda.git dest={{ tools_root }}/exploit-dev/peda force=yes

- name: "git clone pwntools"
  git: repo=https://github.com/Gallopsled/pwntools dest={{ tools_root }}/exploit-dev/pwntools
#- name: "Install pwntools"
#  shell: pip install . chdir=/opt/attacksible/exploit-dev/pwntools

- name: "git clone python-x86-obfuscator"
  git: repo=https://github.com/kgretzky/python-x86-obfuscator dest={{ tools_root }}/exploit-dev/python-x86-obfuscator

- name: "git clone sqlmap"
  git: repo=https://github.com/sqlmapproject/sqlmap.git dest={{ tools_root }}/exploitation/sqlmap
