--- 

- hosts: attacksible
  sudo: yes
  vars: 
    tools_root: /opt/attacksible
    local_user: "{{ lookup('env','USER') }}"
  roles:
    - common
    - system-packages
    - communication-tools
    - handy-tools
#    - network-discovery
    - web-scanning
    - dns-tools
    - smtp-tools
    - os-tools
    - exploit-dev
    - exploit-tools
    - anon-tools
    - mobile
    - network-sniffing
    - layer2n3-attacks
    - password-cracking
    - wifi-tools
    - rfid
    - hardware
    - reverse
    - hdd-forensics
    - wordlists
    - exploit-dev
