--- 

- hosts: attacksible
  vars: 
    attacksible_version: 0.7
    tools_root: /opt/attacksible
    rvm1_rubies:
      - 'ruby-2.3.1' #metasploit
      - 'ruby-2.2.4' #BeEF
      - 'ruby-2.3.1' #stable
    rvm1_install_flags: "--auto-dotfiles --user-install"
    rvm1_install_path: "/home/{{ lookup('env','USER') }}/.rvm"
    local_user: "{{ lookup('env','USER') }}"
    local_group: "{{ lookup('env','USER') }}"
    home_directory: "{{ lookup('env', 'HOME') }}"

  roles:
    - { role: system-packages, tags: always, become: True}
    - { role: common, tags: always, become: True}
    - { role: rvm1, tags: [ruby, always], become: True }
    - { role: anonymisation, tags: anonymisation, become: True }
    - { role: email-tools, tags: email-tools, become: True }
    - { role: exploitation, tags: exploitation, become: True }
    - { role: handy-tools, tags: handy-tools, become: True }
    - { role: hardware, tags: hardware, become: True }
    - { role: forensics, tags: forensics, become: True }
    - { role: mobile, tags: mobile, become: True }
    - { role: network, tags: network, become: True }
    - { role: os-tools, tags: os-tools, become: True }
    - { role: passwords, tags: passwords, become: True }
    - { role: reconnaissance, tags: reconnaissance, become: True }
    - { role: reversing, tags: reversing, become: True }
    - { role: web, tags: web, become: True }
    - { role: wireless, tags: wireless, become: True }
    - { role: wordlists, tags: wordlists, become: True }
    - { role: system-config, tags: system-config, become: True }
