--- 

- hosts: attacksible
  vars: 
    tools_root: /opt/attacksible
    rvm1_rubies:
      - 'ruby-2.3.1' #metasploit
      - 'ruby-2.2.4' #BeEF
      - 'ruby-2.3.0' #stable
    local_user: "{{ lookup('env','USER') }}"
    home_directory: "{{ lookup('env', 'HOME') }}"


  roles:
    - { role: system-packages, tags: always, become: True}
    - { role: common, tags: always, become: True}
    - { role: rvm1, tags: [ruby, always], become: True }
    - { role: anonymisation, tags: anonymisation, become: True }
    - { role: communication-tools, tags: communication-tools, become: True }
    - { role: dns-tools, tags: dns-tools, become: True }
    - { role: exploit-dev, tags: exploit-dev, become: True }
    - { role: exploitation, tags: exploitation, become: True }
    - { role: handy-tools, tags: handy-tools, become: True }
    - { role: hardware, tags: hardware, become: True }
    - { role: forensics, tags: forensics, become: True }
    - { role: layer2n3-attacks, tags: layer2n3-attacks, become: True }
    - { role: mobile, tags: mobile, become: True }
#   - { role: - network-discovery, become: True }
    - { role: network-sniffing, tags: network-sniffing, become: True }
    - { role: os-tools, tags: os-tools, become: True }
    - { role: passwords, tags: passwords, become: True }
    - { role: reversing, tags: reversing, become: True }
    - { role: reconnaissance, tags: reconnaissance, become: True }
    - { role: email-tools, tags: email-tools, become: True }
    - { role: web, tags: web, become: True }
    - { role: wireless, tags: wireless, become: True }
    - { role: wordlists, tags: wordlists, become: True }
    - { role: system-config, tags: system-config, become: True }
