--- 

- hosts: attacksible
  vars: 
    tools_root: /opt/attacksible
  roles:
    - { role: common, become: True }
    - { role: system-packages, become: True }
    - { role: rvm1, tags: ruby, become: True }
    - { role: communication-tools, become: True }
    - { role: handy-tools, become: True }
#    { role: - network-discovery, become: True }
    - { role: web-scanning, become: True }
    - { role: dns-tools, become: True }
    - { role: smtp-tools, become: True }
    - { role: os-tools, become: True }
    - { role: exploit-dev, become: True }
    - { role: exploit-tools, become: True }
    - { role: anon-tools, become: True }
    - { role: mobile, become: True }
    - { role: network-sniffing, become: True }
    - { role: layer2n3-attacks, become: True }
    - { role: password-cracking, become: True }
    - { role: wifi-tools, become: True }
    - { role: rfid, become: True }
    - { role: hardware, become: True }
    - { role: reverse, become: True }
    - { role: hdd-forensics, become: True }
    - { role: wordlists, become: True }
    - { role: exploit-dev, become: True }
