# DNS

- name: "Create dnstools directory"
  file: path={{ tools_root }}/dnstools owner=root state=directory mode=0755

- name: "Package: dnsmap"
  yum: name="dnsmap" state=present

- name: "Package: dnstracer"
  yum: name="dnstracer" state=present
 
- name: "Package: dnsenum"
  yum: name="dnsenum" state=present
 
- name: "Package: lbd"
  yum: name="lbd" state=present

- name: "Git: dnsrecon"
  git: repo=https://github.com/darkoperator/dnsrecon.git dest={{ tools_root }}/dnstools/dnsrecon/
- name: "Install dsnrecon Requirements"
  shell: pip install -r requirements.txt chdir={{ tools_root }}/dnstools/dnsrecon/
