# Exploit tools

- name: "Creating exploit-tools directory"
  file: path={{ tools_root }}/exploit-tools owner=root group=root state=directory mode=0755

## Redhat

- name: "Exploit tools packages"
  yum: name={{ item }} state=present
  with_items:
    - hydra
    - skipfish
  when: ansible_os_family == "RedHat"


- name: "Exploit tools - Fedora-only"
  yum: name={{ item }} state=present
  with_items:
    - sqlninja
  when: ansible_distribution == 'Fedora'

## Debian

- name: "Exploit tools packages"
  apt: name={{ item }} state=present
  with_items:
    - hydra
    - skipfish
  when: ansible_os_family == "Debian"

## All

# https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment
# https://fedoraproject.org/wiki/Metasploit_Postgres_Setup
- name: "git clone Metasploit"
  git: repo=https://github.com/rapid7/metasploit-framework.git dest={{ tools_root }}/exploit-tools/metasploit

- name: "git clone BeEF"
  git: repo=https://github.com/beefproject/beef.git dest={{ tools_root }}/exploit-tools/beef

- name: "git clone Leroy-Jenkins"
  git: repo=https://github.com/captainhooligan/Leroy-Jenkins.git dest={{ tools_root }}/exploit-tools/leroy-jenkins

- name: "Git: NoSQLMap"
  git: repo=https://github.com/tcstool/NoSQLMap.git dest={{ tools_root }}/exploit-tools/nosqlmap

- name: "git clone sqlmap"
  git: repo=https://github.com/sqlmapproject/sqlmap.git dest={{ tools_root }}/exploit-tools/sqlmap

- name: "git clone patator"
  git: repo=https://code.google.com/p/patator dest={{ tools_root }}/exploit-tools/patator

- name: "Creating /opt/burp directory"
  file: path={{ tools_root }}/exploit-tools/burp owner=root group=root state=directory mode=0700
  tags: gui
#- name: "Download: Burp Suite"
#  get_url: url=http://portswigger.net/burp/burpsuite_free_v1.6.01.jar dest={{ tools_root }}/exploit-tools/burp mode=0755
#  tags: gui
- name: "Burp Wrapper"
  copy: src=files/burp dest=/usr/bin/burp mode=0755
  tags: gui

- name: "jboss-autopwn"
  git: repo=https://github.com/SpiderLabs/jboss-autopwn dest={{ tools_root }}/exploit-tools/jboss-autopwn
  tags: untested 

- name: "lisa"
  git: repo=https://github.com/ant4g0nist/lisa.py dest={{ tools_root }}/exploit-dev/lisa
  tags: untested
