# Exploit tools

- name: "Creating exploit-tools directory"
  file: path={{ tools_root }}/exploit-tools owner=root group=root state=directory mode=0755

# https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment
# https://fedoraproject.org/wiki/Metasploit_Postgres_Setup
- name: "git clone Metasploit"
  git: repo=https://github.com/rapid7/metasploit-framework.git dest={{ tools_root }}/exploit-tools/metasploit

- name: "git clone sqlmap"
  git: repo=https://github.com/sqlmapproject/sqlmap.git dest={{ tools_root }}/exploit-tools/sqlmap

- name: "git clone c5scan"
  git: repo=https://github.com/auraltension/c5scan.git dest={{ tools_root }}/exploit-tools/c5scan

- name: "git clone wpscan"
  git: repo=https://github.com/wpscanteam/wpscan.git dest={{ tools_root }}/exploit-tools/wpscan

- name: "git clone patator"
  git: repo=https://code.google.com/p/patator dest={{ tools_root }}/exploit-tools/patator

- name: "Package: hydra"
  yum: name="hydra" state=present

- name: "Package: skipfish"
  yum: name="skipfish" state=present

- name: "Package: sqlninja"
  yum: name="sqlninja" state=present

- name: "Creating /opt/burp directory"
  file: path={{ tools_root }}/exploit-tools/burp owner=root group=root state=directory mode=0700
  tags: gui
- name: "Download: Burp Suite"
  get_url: url=http://portswigger.net/burp/burpsuite_free_v1.5.jar dest={{ tools_root }}/exploit-tools/burp mode=0755
  tags: gui
- name: "Burp Wrapper"
  copy: src=files/burp dest=/usr/bin/burp mode=0755
  tags: gui
