# Discovery / Information Gathering
# Network Discovery / Scanning  

- name: "Create info-discovery directory"
  file: path={{ tools_root }}/info-discovery owner=root state=directory mode=0700

- name: "Package: nmap"
  yum: pkg=nmap state=latest

- name: "Package: onesixtyone"    
  yum: name="onesixtyone" state=present                                                                                                            
- name: "Package: snmpcheck"
  yum: name="snmpcheck" state=present                                                                                                              
- name: "Package: fping"
  yum: name="fping" state=present                                                                                                                  
- name: "Package: tcping"
  yum: name="tcping" state=present                                                                                                                  
- name: "Package: nbtscan"
  yum: name="nbtscan" state=present                                                                                                                
- name: "Package: hping3"
  yum: name="hping3" state=present                                                                                                                 
- name: "Package: intrace"
  yum: name="intrace" state=present

- name: "File: fierce.pl"
  copy: src=fierce.pl dest={{ tools_root }}/info-discovery/

- name: "Git: recon-ng"
  git: repo=https://bitbucket.org/LaNMaSteR53/recon-ng.git dest={{ tools_root }}/info-discovery/recon-ng

- name: "Download enum4linux Samba Enumerator"
  get_url: url=https://labs.portcullis.co.uk/download/enum4linux-0.8.9.tar.gz dest=/tmp/enum4linux.tar.gz
- name: "Create metagoofil directory"
  file: path={{ tools_root }}/info-discovery/enum4linux owner=root state=directory mode=0700
- name: "Extract enaum4linux"
  command: tar -xzf /tmp/enum4linux.tar.gz -C {{ tools_root }}/info-discovery/enum4linux

- name: "Download MetaGoofil public document metadata extractor"
  get_url: url=https://metagoofil.googlecode.com/files/metagoofil-2.2.tar.gz dest=/tmp/metagoofil.tar.gz
- name: "Create metagoofil directory"
  file: path={{ tools_root }}/info-discovery/metagoofil owner=root state=directory mode=0700
- name: "Extract MetaGoofil"
  command: tar -xzf /tmp/metagoofil.tar.gz -C {{ tools_root }}/info-discovery/metagoofil

- name: "Git: wfuzz"
  git: repo=https://github.com/xmendez/wfuzz.git dest={{ tools_root }}/info-discovery/wfuzz
