# Discovery / Information Gathering
# Network Discovery / Scanning  

- name: "Create info-discovery directory"
  file: path={{ tools_root }}/info-discovery owner=root state=directory mode=0755

## Redhat
- name: "network Discovery & Scanning Packages"
  yum: pkg={{ item }} state=latest
  with_items:
    - hping3
    - nmap
    - onesixtyone
    - snmpcheck
    - fping
    - tcping
  when: ansible_os_family == "RedHat"

- name: "Network Discovery - Fedora-only packages"
  yum: name={{ item }} state=present
  with_items:
    - nbtscan
    - intrace
  when: ansible_distribution == 'Fedora'

## Debian
- name: "network Discovery & Scanning Packages"
  apt: pkg={{ item }} state=latest
  with_items:
    - hping3
    - nmap
    - onesixtyone
    - fping
    - nbtscan
  when: ansible_os_family == "Debian"

## All

- name: "File: fierce.pl"
  copy: src=files/fierce.pl dest={{ tools_root }}/info-discovery/

- name: "Git: recon-ng"
  git: repo=https://bitbucket.org/LaNMaSteR53/recon-ng.git dest={{ tools_root }}/info-discovery/recon-ng

- name: "Git: masscan"
  git: repo=https://github.com/robertdavidgraham/masscan dest={{ tools_root }}/info-discovery/masscan

- name: "Git: fast-recon"
  git: repo=https://github.com/DanMcInerney/fast-recon dest={{ tools_root }}/info-discovery/fast-recon

- name: "Download enum4linux Samba Enumerator"
  get_url: url=https://labs.portcullis.co.uk/download/enum4linux-0.8.9.tar.gz dest=/tmp/enum4linux.tar.gz
- name: "Create enum4linux directory"
  file: path={{ tools_root }}/info-discovery/enum4linux owner=root state=directory mode=0755
- name: "Extract enum4linux"
  command: tar -xzf /tmp/enum4linux.tar.gz -C {{ tools_root }}/info-discovery/enum4linux

- name: "Download MetaGoofil public document metadata extractor"
  get_url: url=https://metagoofil.googlecode.com/files/metagoofil-2.2.tar.gz dest=/tmp/metagoofil.tar.gz
- name: "Create metagoofil directory"
  file: path={{ tools_root }}/info-discovery/metagoofil owner=root state=directory mode=0755
- name: "Extract MetaGoofil"
  command: tar -xzf /tmp/metagoofil.tar.gz -C {{ tools_root }}/info-discovery/metagoofil

- name: "miranda-upnp"
  subversion: repo=http://miranda-upnp.googlecode.com/svn/trunk/ dest={{ tools_root }}/network-discovery/miranda-upnp

- name: "Remove tmp directories"
  command: rm {{ item }}
  with_items:
    - /tmp/metagoofil.tar.gz
    - /tmp/enum4linux.tar.gz
