  # Reverse Engineering / Decompilers
  - name: "Reversing, Decompilers"
    yum: name={{ item }} state=present
    with_items:
      - edb
      - binwalk
      - flasm
    when: ansible_distribution == 'Fedora'
