# System Packages / Dev Packages
# Firewall rules / Antivirus / Logging / OS House clean / System Debug Tools

- name: "System packages"
  yum: name={{ item }} state=present
  with_items:
    - '"@Development tools"'
    - clang
    - dhcp
    - patch
    - pth
    - clamav
    - ferm
    - htop
    - lighttpd
    - postgresql-server
    - postgresql-devel
    - postgresql
    - python
    - python-pip
    - python-devel
    - ruby-devel
    - rubygem-bundler
    - java-openjdk
    - net-snmp-utils
    - vim-enhanced
    - libpcap
    - libpcap-devel
    - p7zip
    - lldb
    - zlib-devel
  when:
    - ansible_os_family == "RedHat"

- name: "System packages"
  apt: name={{ item }} state=present
  with_items:
#    - '"@Development tools"'
    - clang
    - curl
    - patch
#    - pth
    - clamav
    - ferm
    - htop
    - lighttpd
    - postgresql
    - postgresql-server-dev-all
    - postgresql
    - python
    - python-pip
    - python-dev
    - ruby-dev
    - bundler
    - openjdk-8-jdk
    - snmp
    - vim
    - libpcap-dev
    - p7zip
    - lldb
    - zlib1g-dev
    - subversion
    - libsqlite3-dev
  when:
    - ansible_os_family == "Debian"

- name: "Fedora-only sys-packages"
  yum: name={{ item }} state=present
  with_items:
    - tsocks
    - pylibpcap
  when: ansible_distribution == 'Fedora'

- name: "GUI environment sys-packages"
  yum: name=terminator state=present
  when:
    - ansible_os_family == "RedHat"
  tags: gui

- name: "Untested sys-packages"
  yum: name=http://keepnote.org/download/keepnote-0.7.8-1.noarch.rpm state=present
  when:
    - ansible_os_family == "RedHat"
  tags: untested

- name: "Pip packages"
  shell: pip install {{ item }} 
  with_items:
    - pyinstaller
