# Web Scanning
- name: "Web Scanning - Fedora-only packages"
  yum: name={{ item }} state=present
  with_items: 
    - nikto
  when: ansible_distribution == 'Fedora'
 
- name: "Web Scanning Packages"
  yum: name={{ item }} state=present
  with_items:
    - ssldump
    - sslscan
  when: ansible_os_family == "RedHat"

- name: "Git: wfuzz"
  git: repo=https://github.com/xmendez/wfuzz.git dest={{ tools_root }}/web-scanning/wfuzz

- name: "Git: dvcs-ripper"
  git: repo=https://github.com/kost/dvcs-ripper.git dest={{ tools_root }}/web-scanning/dvcs-ripper
  tags: untested

- name: "git clone c5scan"
  git: repo=https://github.com/auraltension/c5scan.git dest={{ tools_root }}/web-scanning/c5scan

- name: "git clone wpscan"
  git: repo=https://github.com/wpscanteam/wpscan.git dest={{ tools_root }}/web-scanning/wpscan
- name: "bundle install for wpscan"
  shell: bundle install chdir={{ tools_root }}/web-scanning/wpscan
