# RFID

## Redhat
- name: "Package: libnfc and examples"
  package: name={{ item }} state=present
  with_items:
    - libnfc
    - libnfc-examples
  when: ansible_distribution == 'Fedora'

## Redhat
- name: "Package: libnfc and examples"
  package: name={{ item }} state=present
  with_items:
    - libnfc-dev
    - libnfc-examples
  when: ansible_distribution == 'Debian'

## All
- name: "mfcuk"
  git: repo=https://github.com/nfc-tools/mfcuk.git dest={{ tools_root }}/rfid/mfcuk

- name: "mfoc"
  git: repo=https://github.com/nfc-tools/mfoc.git dest={{ tools_root }}/rfid/mfcoc
