# Hardware Hacking

- name: "Creating hardware directory"
  file: path={{ tools_root }}/hardware owner=root group=root state=directory mode=0755

- name: "Get duckencoder for USB Rubber Ducky"
  get_url: 
    url: https://github.com/midnitesnake/USB-Rubber-Ducky/raw/master/Encoder/encoder.jar
    dest: "{{ tools_root }}/hardware/duckencode.jar"
    mode: 0755

- name: "Packages for hardware devices"
  package: name={{ item }} state=present
  with_items:
    - minicom
    - arduino
