# System Packages / Dev Packages
# Firewall rules / Antivirus / Logging / OS House clean / System Debug Tools

## REDHAT

- name: "System packages"
  yum: name={{ item }} state=present
  with_items:
    - '@Development tools'
    - clang
    - dhcp
    - patch
    - pth
    - clamav
    - ferm
    - htop
    - lighttpd
    - mysql
    - postgresql-server
    - postgresql-devel
    - postgresql
    - python
    - python-devel
    - ruby-devel
    - rubygem-bundler
    - java-openjdk
    - net-snmp-utils
    - vim-enhanced
    - libpcap
    - libpcap-devel
    - p7zip
    - lldb
    - zlib-devel
    - http://keepnote.org/download/keepnote-0.7.8-1.noarch.rpm
  when:
    - ansible_os_family == "RedHat"

- name: "Fedora-only sys-packages"
  yum: name={{ item }} state=present
  with_items:
    - tsocks
    - pylibpcap
  when: ansible_distribution == 'Fedora'

- name: "GUI environment sys-packages"
  yum: name=terminator state=present
  when:
    - ansible_os_family == "RedHat"
  tags: gui


## DEBIAN

- name: "System packages"
  apt: name={{ item }} state=present
  with_items:
#    - '"@Development tools"'
    - clang
    - curl
    - patch
#    - pth
    - clamav
    - ferm
    - htop
    - keepnote
    - libcapstone-dev
    - lighttpd
    - mysql-client
    - postgresql
    - postgresql-server-dev-all
    - postgresql
    - python
    - python-dev
    - ruby-dev
    - bundler
    - openjdk-8-jdk
    - snmp
    - vim
    - libpcap-dev
    - p7zip
    - python-libpcap
    - tsocks
    - lldb
    - zlib1g-dev
    - subversion
    - libsqlite3-dev
  when:
    - ansible_os_family == "Debian"

- name: "GUI environment sys-packages"
  apt: name=terminator state=present
  when:
    - ansible_os_family == "Debian"
  tags: gui

## All

- name: Make sure pip is installed
  command: easy_install -U pip

- name: Fix pip permissions
  file:
    path: /usr/local/bin/pip
    mode: 0750

- name: "Pip packages"
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pyinstaller
    - psycopg2

- name: Inititialise Postgres
  command: postgresql-setup initdb
  ignore_errors: yes

- name: Start postgresql
  service: name=postgresql enabled=no state=started
