# System Packages / Dev Packages
# Firewall rules / Antivirus / Logging / OS House clean / System Debug Tools


## FEDORA

- name: "System packages"
  package: name={{ item }} state=present
  with_items:
    - '@Development tools'
    - dhcp
    - pth
    - libselinux-python
    - mysql
    - postgresql-server
    - postgresql-devel
    - python-devel
    - ruby-devel
    - rubygem-bundler
    - java-openjdk
    - net-snmp-utils
    - vim-enhanced
    - redhat-rpm-config
    - libpcap
    - libpcap-devel
    - pylibpcap
    - python-dnf-plugins-core
    - zlib-devel
    - http://keepnote.org/download/keepnote-0.7.8-1.noarch.rpm
  when: ansible_distribution == 'Fedora'

## DEBIAN

- name: "System packages"
  package: name={{ item }} state=present
  with_items:
    - curl
    - keepnote
    - libcapstone-dev
    - mysql-client
    - postgresql
    - postgresql-server-dev-all
    - python-dev
    - ruby-dev
    - bundler
    - openjdk-8-jdk
    - snmp
    - vim
    - libpcap-dev
    - python-libpcap
    - zlib1g-dev
    - subversion
    - libsqlite3-dev
  when:
    - ansible_os_family == "Debian"

## All

- name: "System packages"
  package: name={{ item }} state=present
  with_items:
    - clamav
    - clang
    - ferm
    - htop
    - lighttpd
    - lldb
    - patch
    - p7zip
    - postgresql
    - python
    - python-setuptools
    - tsocks
    - weechat
    - xterm

- name: "GUI environment sys-packages"
  package: name=terminator state=present
  tags: gui

- name: Make sure pip is installed
  command: easy_install -U pip

- name: Fix pip permissions
  file:
    path: /usr/local/bin/pip
    mode: 0750
  ignore_errors: yes

- name: "Pip packages"
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pyinstaller
    - psycopg2

- name: Inititialise Postgres
  command: postgresql-setup initdb
  ignore_errors: yes

- name: Start postgresql
  service: name=postgresql enabled=no state=started

# Tools

## Redhat
- name: "Handy Tools"
  package: name={{ item }} state=present
  with_items:
    - ipcalculator
    - perl-Image-ExifTool
    - ShellCheck
  when: ansible_distribution == 'Fedora'

## Debian
- name: "Handy Tools"
  package: name={{ item }} state=present
  with_items:
    - ipcalc
    - libimage-exiftool-perl
    - shellcheck
  when: ansible_os_family == "Debian"

# ALL
- name: "Handy Tools"
  package: name={{ item }} state=present
  with_items:
    - cadaver
    - ike
    - macchanger
    - md5deep
    - ngrep
    - screen
    - socat
    - tcplay
    - tmux

- name: "Handy tools for Desktops"
  package: name={{ item }} state=present
  with_items:
    - keepassx
    - recordmydesktop
  tags: gui
