# Wireless 

## Redhat
- name: "Wifi tools"
  package: name={{ item }} state=present
  with_items:
    - iw
    - hostapd
    - wavemon
  when: ansible_os_family == "RedHat"

- name: "Wifi tools - Fedora only"
  package: name={{ item }} state=present
  with_items:
    - aircrack-ng
    - kismet
  when: ansible_distribution == 'Fedora'

- name: "Package: gnuradio"
  package: name="gnuradio" state=present
  when: ansible_os_family == "RedHat"
  tags: gui

## Debain
- name: "Wifi tools"
  package: name={{ item }} state=present
  with_items:
    - iw
    - hostapd
    - wavemon
    - aircrack-ng
    - kismet
  when: ansible_os_family == "Debian"

- name: "Package: gnuradio"
  package: name="gnuradio" state=present
  when: ansible_os_family == "Debian"
  tags: gui

## All
- name: "Git: wifite"
  git: repo=https://github.com/derv82/wifite dest={{ tools_root }}/wireless/wifi/wifite
  tags: untested

- name: "Git: wifijammer"
  git: repo=https://github.com/DanMcInerney/wifijammer.git dest={{ tools_root }}/wireless/wifi/wifijammer

    # No more google code.
#- name: "reaver-wps"
  #  subversion: repo=http://reaver-wps.googlecode.com/svn/trunk/ dest={{ tools_root }}/wireless/wifi/reaver-wps
  #  tags: untested

# RFID

## Redhat
- name: "Package: libnfc and examples"
  package: name={{ item }} state=present
  with_items:
    - libnfc
    - libnfc-examples
  when: ansible_distribution == 'Fedora'

## Redhat
- name: "Package: libnfc and examples"
  package: name={{ item }} state=present
  with_items:
    - libnfc-dev
    - libnfc-examples
  when: ansible_distribution == 'Debian'

## All


- name: "Git: mfcuk"
  git: repo=https://github.com/nfc-tools/mfcuk.git dest={{ tools_root }}/wireless/rfid/mfcuk

- name: "Git: mfoc"
  git: repo=https://github.com/nfc-tools/mfoc.git dest={{ tools_root }}/wireless/rfid/mfoc


