# Wireless 

## All
- name: "Wifi tools"
  package: name={{ item }} state=present
  with_items:
    - iw
    - hostapd
    - libnfc-examples
    - wavemon
    - aircrack-ng
    - kismet

- name: "Git: gnuradio"
  package: 
    name: "gnuradio"
    state: present
  tags: gui

## Redhat
- name: "Package: libnfc and examples"
  package: name={{ item }} state=present
  with_items:
    - libnfc
  when: ansible_distribution == 'Fedora'

## Debian
- name: "Package: libnfc and examples"
  package: name={{ item }} state=present
  with_items:
    - libnfc-dev
  when: ansible_distribution == 'Debian'

- name: "Git: airgeddon"
  git:
    repo: https://github.com/v1s1t0r1sh3r3/airgeddon.git
    dest: "{{ tools_root }}/wireless/wifi/airgeddon"
  tags: gui

- name: "Git: mfcuk"
  git: 
    repo: https://github.com/nfc-tools/mfcuk.git
    dest: "{{ tools_root }}/wireless/rfid/mfcuk"

- name: "Git: mfoc"
  git: 
    repo: https://github.com/nfc-tools/mfoc.git
    dest: "{{ tools_root }}/wireless/rfid/mfoc"

- name: "Git: wifijammer"
  git: 
    repo: https://github.com/DanMcInerney/wifijammer.git
    dest: "{{ tools_root }}/wireless/wifi/wifijammer"

- name: "Git: wifite"
  git: 
    repo: https://github.com/derv82/wifite
    dest: "{{ tools_root }}/wireless/wifi/wifite"

## No more google code.
#- name: "reaver-wps"
  #  subversion: repo=http://reaver-wps.googlecode.com/svn/trunk/ dest={{ tools_root }}/wireless/wifi/reaver-wps
  #  tags: untested

