# Anonymity

## Redhat
- name: "Anonymity and proxy tools - Packages"
  yum: pkg={{ item }} state=latest
  with_items:
    - tor
    - stunnel
    - iodine
  when: ansible_os_family == "RedHat"


- name: "Anonymity and proxy tools - Packages (Fedora)"
  yum: name={{ item }} state=present
  with_items:
    - proxychains
    - proxytunnel
  when: ansible_distribution == 'Fedora'

## Debian
- name: "Anonymity and proxy tools (Packages)"
  apt: pkg={{ item }} state=latest
  with_items:
    - tor
    - stunnel
    - iodine
    - proxychains
    - proxytunnel
  when: ansible_os_family == "Debian"

## All
- name: "Git: Onionshare"
  git: repo=https://github.com/micahflee/onionshare dest={{ tools_root }}/anon-tools/onionshare
  tags: untested
