---

- name: "Creating exploit-tools directory"
  file: path={{ tools_root }}/exploit-tools owner=root group=root state=directory mode=0755

## Redhat

- name: "Exploit tools packages"
  yum: name={{ item }} state=present
  with_items:
    - hydra
    - skipfish
  when: ansible_os_family == "RedHat"


- name: "Exploit tools - Fedora-only"
  yum: name={{ item }} state=present
  with_items:
    - sqlninja
  when: ansible_distribution == 'Fedora'

## Debian

- name: "Exploit tools packages"
  apt: name={{ item }} state=present
  with_items:
    - hydra
    - skipfish
  when: ansible_os_family == "Debian"

## All

  #TODO: bundle install
- name: "Postgres: Allow local connections for Metasploit setup"
  replace: dest=/var/lib/pgsql/data/pg_hba.conf
           regexp='local\s+all\s+all\s+peer'
           replace='local all all trust'
  notify: 
    - restart postgresql
  when: ansible_os_family == "RedHat"
- name: "Postgres: Allow local connections for Metasploit setup"
  replace: dest=/etc/postgresql/9.4/main/pg_hba.conf
           regexp='local\s+all\s+postgres\s+peer'
           replace='local all postgres trust'
  notify: 
    - restart postgresql
  when: ansible_os_family == "Debian"
- meta: flush_handlers
- name: "Metasploit: Git"
  git: repo=https://github.com/rapid7/metasploit-framework.git dest={{ tools_root }}/exploit-tools/metasploit
- name: "Metasploit: Postgres user"
  postgresql_user: name=msf password=msf role_attr_flags=NOSUPERUSER,NOCREATEROLE,NOCREATEDB
- name: "Metasploit: Postgres DB"
  postgresql_db: name=msf owner=msf
- name: "metasploit: database.yml config"
  template: src=msf-database.yml.j2 dest={{ tools_root }}/exploit-tools/metasploit/config/database.yml mode=0640
- name: "Metasploit: Add line in pg_hba.conf"
  lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
              regexp='host\s+msf\s+msf\s+127.0.0.1/32\s+md5'
              line='host msf msf 127.0.0.1/32 md5'
              insertafter='#\s+TYPE\s+DATABASE\s+USER'
              state=present
  when: ansible_os_family == "RedHat"
- name: "Metasploit: Add line in pg_hba.conf"
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              regexp='host\s+msf\s+msf\s+127.0.0.1/32\s+md5'
              line='host msf msf 127.0.0.1/32 md5'
              insertafter='#\s+TYPE\s+DATABASE\s+USER'
              state=present
  when: ansible_os_family == "Debian"
- name: "Postgres: Reset local connections to 'peer' after Metasploit setup"
  replace: dest=/var/lib/pgsql/data/pg_hba.conf
           regexp='local\s+all\s+all\s+trust'
           replace='local all all peer'
  notify:
    - restart postgresql
  when: ansible_os_family == "RedHat"
- name: "Postgres: Reset local connections to 'peer' after Metasploit setup"
  replace: dest=/etc/postgresql/9.4/main/pg_hba.conf
           regexp='local\s+all\s+postgres\s+trust'
           replace='local all postgres peer'
  notify:
    - restart postgresql
  when: ansible_os_family == "Debian"
- meta: flush_handlers

- name: "git clone BeEF"
  git: repo=https://github.com/beefproject/beef.git dest={{ tools_root }}/exploit-tools/beef

- name: "git clone Leroy-Jenkins"
  git: repo=https://github.com/captainhooligan/Leroy-Jenkins.git dest={{ tools_root }}/exploit-tools/leroy-jenkins

- name: "Git: NoSQLMap"
  git: repo=https://github.com/tcstool/NoSQLMap.git dest={{ tools_root }}/exploit-tools/nosqlmap

- name: "git clone sqlmap"
  git: repo=https://github.com/sqlmapproject/sqlmap.git dest={{ tools_root }}/exploit-tools/sqlmap

- name: "git clone patator"
  git: repo=https://code.google.com/p/patator dest={{ tools_root }}/exploit-tools/patator

- name: "Creating /opt/burp directory"
  file: path={{ tools_root }}/exploit-tools/burp owner=root group=root state=directory mode=0700
  tags: gui
#- name: "Download: Burp Suite"
#  get_url: url=http://portswigger.net/burp/burpsuite_free_v1.6.01.jar dest={{ tools_root }}/exploit-tools/burp mode=0755
#  tags: gui
- name: "Burp Wrapper"
  copy: src=burp dest=/usr/bin/burp mode=0755
  tags: gui

- name: "jboss-autopwn"
  git: repo=https://github.com/SpiderLabs/jboss-autopwn dest={{ tools_root }}/exploit-tools/jboss-autopwn
  tags: untested 

- name: "lisa"
  git: repo=https://github.com/ant4g0nist/lisa.py dest={{ tools_root }}/exploit-tools/lisa
  tags: untested
