# Network tools

## Redhat
- name: "Packages: Network Tools"
  package: name={{ item }} state=present
  with_items:
    - lbd
    - dnsenum
    - dnsmap
    - ettercap
    - intrace
    - sipp
    - snmpcheck
    - sslsplit
    - tcping
    - wol
  when: ansible_distribution == 'Fedora'

## Debian
- name: "Packages: Network Tools"
  package: name={{ item }} state=present
  with_items:
    - ettercap-text-only
    - mitmproxy
    - wakeonlan
  when: ansible_os_family == "Debian"

- name: "packages: Network Tools (graphical)"
  package: name={{ item }} state=present
  with_items:
    - ettercap-graphical
  when: ansible_os_family == "Debian"
  tags: gui

## All
- name: "Packages: Network tools"
  package: name={{ item }} state=present
  with_items:
    - dnstracer
    - dsniff
    - sipsak
    - sslstrip
    - tcpflow
    - tcpreplay
    - wireshark
    - yersinia
    - hping3
    - nmap
    - onesixtyone
    - fping
    - nbtscan
 
- name: "git clone dnsrecon"
  git: repo=https://github.com/darkoperator/dnsrecon.git dest={{ tools_root }}/network/dnsrecon/
- name: "pip: Install dsnrecon requirements"
  shell: pip install -r requirements.txt chdir={{ tools_root }}/network/dnsrecon/

- name: "git clone fierce"
  git: repo=https://github.com/mschwager/fierce.git dest={{ tools_root }}/network/fierce

- name: "git clone masscan"
  git: repo=https://github.com/robertdavidgraham/masscan dest={{ tools_root }}/network/masscan

- name: "git clone MITMf"
  git: repo=https://github.com/byt3bl33d3r/MITMf.git dest={{ tools_root }}/network/MITMf

- name: "git clone net-creds"
  git: repo=https://github.com/DanMcInerney/net-creds.git dest={{ tools_root }}/network/net-creds
