# DNS

- name: "DNS tools - Create dnstools directory"
  file: path={{ tools_root }}/dnstools owner=root state=directory mode=0755

## Redhat

- name: "DNS tools  - Packages"
  package: name={{ item }} state=present
  with_items:
    - lbd
    - dnsmap
  when: ansible_os_family == "RedHat"


- name: "DNS tools - Packages (Fedora)"
  package: name={{ item }} state=present
  with_items:
    - dnstracer
    - dnsenum
  when: ansible_distribution == 'Fedora'

## Debian

- name: "DNS tools - Packages"
  apt: name={{ item }} state=present
  with_items:
    - dnstracer
  when: ansible_os_family == "Debian"

## All
 
- name: "Git: dnsrecon"
  git: repo=https://github.com/darkoperator/dnsrecon.git dest={{ tools_root }}/dnstools/dnsrecon/
- name: "Install dsnrecon Requirements"
  shell: pip install -r requirements.txt chdir={{ tools_root }}/dnstools/dnsrecon/


- name: "Git: fierce"
  git: repo=https://github.com/mschwager/fierce.git dest={{ tools_root }}/dnstools/fierce
