# Reverse Engineering / Decompilers

## Redhat
- name: "Reversing, Decompilers"
  package: name={{ item }} state=present
  with_items:
    - edb
    - binwalk
    - flasm
  when: ansible_distribution == 'Fedora'

## Debian
- name: "Reversing, Decompilers"
  package: name={{ item }} state=present
  with_items:
    - edb
    - binwalk
    - flasm
  when: ansible_distribution == 'Debian'

# All
- name: "Git: toby"
  git: repo=https://github.com/byt3bl33d3r/toby.git dest={{ tools_root}}/reversing/toby

- name: "Git: reversetools"
  git: repo=https://framagit.org/BeHuman/reversetools.git dest={{ tools_root}}/reversing/reversetools
  tags: gui
