# Web Scanning

- name: "Web Scanning Packages"
  package: name={{ item }} state=present
  with_items:
    - nikto
    - skipfish 
    - ssldump
    - sslscan
    - testssl

- name: "Git: wfuzz"
  git: repo=https://github.com/xmendez/wfuzz.git dest={{ tools_root }}/web/wfuzz

- name: "Git: dvcs-ripper"
  git: repo=https://github.com/kost/dvcs-ripper.git dest={{ tools_root }}/web/dvcs-ripper

- name: "Git: c5scan"
  git: repo=https://github.com/auraltension/c5scan.git dest={{ tools_root }}/web/c5scan

- name: "Git: wpscan"
  git: repo=https://github.com/wpscanteam/wpscan.git dest={{ tools_root }}/web/wpscan

- name: "wpscan: bundle install"
  shell: bundle install chdir={{ tools_root }}/web/wpscan
