# Web Scanning

- name: "Web Scanning Packages"
  package: name={{ item }} state=present
  with_items:
    - nikto
    - skipfish 
    - ssldump
    - sslscan

- name: "Web Scanning Packages: Fedora only"
  package: name={{ item }} state=present
  with_items:
    - testssl
  when: ansible_os_family == "Redhat"

- name: "Web Scanning Packages: Debian only"
  package: name={{ item }} state=present
  with_items:
    - testssl.sh
  when: ansible_os_family == "Debian"

- name: "Web scanning: pip packages"
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - sslyze

- name: "Git: wfuzz"
  git: repo=https://github.com/xmendez/wfuzz.git dest={{ tools_root }}/web/wfuzz

- name: "Git: dvcs-ripper"
  git: repo=https://github.com/kost/dvcs-ripper.git dest={{ tools_root }}/web/dvcs-ripper

- name: "Git: c5scan"
  git: repo=https://github.com/auraltension/c5scan.git dest={{ tools_root }}/web/c5scan

- name: "Git: wpscan"
  git: repo=https://github.com/wpscanteam/wpscan.git dest={{ tools_root }}/web/wpscan

- name: "wpscan: bundle install"
  shell: bundle install chdir={{ tools_root }}/web/wpscan
