# Forensics tools

## Redhat
- name: "Forensics packages"
  package: name={{ item }} state=present
  with_items:
    - ddrescue
    - sleuthkit-devel
  when: ansible_distribution == 'Fedora'

## Debian
- name: "Forensics packages"
  package: name={{ item }} state=present
  with_items:
    - gddrescue
    - sleuthkit-dev
  when: ansible_os_family == "Debian"

## All
- name: "Forensics packages"
  package: name={{ item }} state=present
  with_items:
    - dc3dd
    - dcfldd
    - scalpel
    - testdisk
    - extundelete
    - foremost
    - safecopy
    - sleuthkit
    - recoverjpeg
