# Password Cracking
# Write app to crack in the cloud.

## Redhat
- name: "Password cracking packages"
  package: name={{ item }} state=present
  with_items:
    - medusa
    - sucrack
    - samdump2
  when: ansible_os_family == "RedHat"

- name: "Password cracking - Fedora-only packages"
  package: name={{ item }} state=present
  with_items:
    - ncrack
    - john
    - ophcrack
    - cowpatty
    - pyrit
    - chntpw
  when: ansible_distribution == 'Fedora'

## Debian
- name: "Password cracking packages"
  apt: name={{ item }} state=present
  with_items:
    - medusa
    - sucrack
    - samdump2
    - john
    - ophcrack
    - pyrit
    - chntpw
  when: ansible_os_family == "Debian"

## All

- name: "HashID"
  git: repo=https://github.com/psypanda/hashID.git dest={{ tools_root }}/password-cracking/hashID
